#### Importando librería Numpy


In [1]:
import numpy as np

##### Creando una lista de 10 datos


In [2]:
lista = list(range(1,11))
lista1 = [1,2,3,4,5,6,7,8,9,10]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### tranformando la lista en un array

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de objeto

In [4]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de dato que contiene el arreglo


In [5]:
arreglo.dtype

dtype('int32')

##### definir como float32

In [6]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### sigue siendo un array de int32


In [7]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformar datos en float32

In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### funcion similar a range pero ocupando arrays


##### funciones en numpy


In [ ]:
promedio = np.mean(arreglo)
promedio

##### Desviacion estandar

In [ ]:
desviacion_std = np.std(arreglo)
desviacion_std

##### Generacion de un arreglo de 10 elementos de solo unos

In [10]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### Transformando arreglo de unos de flotantes a enteros

In [11]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

##### arreglode ceros

In [12]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

##### Generando un arreglo de numeros aleatorios de 5 elementos

In [27]:
arreglo_aleatorio = np.random.rand(3)
arreglo_aleatorio

array([0.29428758, 0.33769639, 0.8187987 ])

##### Generando arreglo aleatorio de 10 numeros enteros del 1 al 5

In [57]:
arreglo_aleatorio2 = np.random.randint(1, 5, 5)
arreglo_aleatorio2

array([1, 2, 1, 5, 5])

##### Generar matriz aleatoria

In [47]:
matriz = np.random.rand(3,3)
matriz

array([[0.20557676, 0.34463286, 0.89170343],
       [0.58356538, 0.48673962, 0.89743053],
       [0.67770542, 0.24013532, 0.01516022]])

##### Matriz aleatoria de 10x10 de números int del 1 al 100

In [52]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[ 38,  61,   2,  74,  42,   1,  26,  82,  19,  53],
       [  4,  71,  68,   2,  79,   1,  79,  49,  42,  82],
       [ 61,  82,  68,  65,  67,  57,  65,  35,  46,  61],
       [ 64,  87,  22,  37,  24,  70,  19,  74,  25,  96],
       [ 60,  49,  34,  50,  32,   1,  33,  39,  84,  96],
       [ 92,  40,  13,   2,  48,  33,  43,  67,   2,  71],
       [ 33,  46,  95,  93,  40,  73,  61,  98,  32,  26],
       [ 42,  56,  52,  49,  97,  65,  47,  95,  32,  44],
       [ 43,  89,  65,  26,  85,  15,  60,  94,  10,  28],
       [100,   1,  34,  25,   6,  43,  39,   9,  14,  94]])